### ISSUE TITLE
Needs "DefaultSSLClient" creation

### ISSUE THREAD

**Issue by evshvarov** [CraigRegester/fit-rest-operation-framework#1]
Great lib! A minor thing - it demands "DefaultSSLClient" SSL configuration.
Could be installed via [one-liner](https://github.com/evshvarov/isc-one-liners/blob/7ec7229c9e019d87dd31de11e60cbb8b8d8d02bf/src/dc/one/Line.cls#L11):
    x "n $namespace set $namespace=""%SYS"", name=""DefaultSSLClient"" do:'##class(Security.SSLConfigs).Exists(name) ##class(Security.SSLConfigs).Create(name)"

**Comment by CraigRegester** [comment]
Thanks @evshvarov ! Agree, definitely on my list to add as part of the zpm piece as well. Been struggling to find time to work on my 'pet projects' but appreciate all the feedback regardless!
